Create .gitignore
H00pyFr00d/edinburgh-uni-learn-login pull request #1
Opened 2022-03-28 18:53 UTC by bvechiato

2022-03-28 21:20 UTC, arjunnaha requested changes

2022-03-28 21:20 UTC, arjunnaha commented on .gitignore
> +*.txt
Add `user-info.txt`

2022-03-29 13:53 UTC, bvechiato commented on .gitignore
> +*.txt
does *.txt not include userinfo

2022-03-29 13:54 UTC, arjunnaha commented on .gitignore
> +*.txt
Yea I was being retarded

2022-03-29 14:06 UTC, arjunnaha approved these changes

2022-04-02 15:16 UTC, merged